definitions:
  handler.SigninRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handler.SigninResponse:
    properties:
      access_token:
        type: string
    type: object
  handler.SignupRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  handler.SignupResponse:
    properties:
      access_token:
        type: string
    type: object
  handler.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/health-check:
    get:
      description: Verify health check application
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Health Check
      tags:
      - Health Check
  /api/v1/current/user:
    get:
      description: Find user logged
      produces:
      - application/json
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/handler.UserResponse'
      security:
      - BearerAuth: []
      summary: User Logged
      tags:
      - User
  /api/v1/signin:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Login User
        in: body
        name: signin
        required: true
        schema:
          $ref: '#/definitions/handler.SigninRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tokens
          schema:
            $ref: '#/definitions/handler.SigninResponse'
      summary: Sign In
      tags:
      - Sign In
  /api/v1/signup:
    post:
      consumes:
      - application/json
      description: Create new User
      parameters:
      - description: New User
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/handler.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tokens
          schema:
            $ref: '#/definitions/handler.SignupResponse'
      summary: Sign Up
      tags:
      - Sign Up
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
